style.fill: transparent

fortran: {
    label: Fortran Source
    style.font-color: white
    style.fill: lightsteelblue
    openmp {
        label: OpenMP
    }
    do_conc {
        label: do concurrent
        style.font: mono
    }
}

cuda_cpp {
    label: CUDA\n(C++)
}

cpp {
    label: C++ source
    style.font-color: white
    style.fill: lightsteelblue
    openmp {
        label: OpenMP
    }
}

ptx {
    label: PTX
}

sass {
    label: GPU bytecode (SASS)
}

fortran.openmp -> ptx {
    style.stroke: white
}
cpp.openmp -> ptx: nvc++ {
    style.stroke: white
    style.font-color: white
}
fortran.do_conc -> ptx: nvfortran {
    style.stroke: white
    style.font-color: white
}
python -> ptx: Numba {
    style.stroke: white
    style.font-color: white
}
cuda_cpp -> ptx: nvcc {
    style.stroke: white
    style.font-color: white
}
ptx -> sass {
    style.stroke: white
}
